const fs=require('node:fs'),path=require('node:path'),{chromium}=require(path.join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const out=path.resolve(process.env.PITCH_ART_EVIDENCE || path.join(__dirname,'../../.visual-review/glasspitch-round2/art/regression'));const targetUrl=new URL(process.env.PITCH_URL || 'http://127.0.0.1:5261');targetUrl.searchParams.set('test','1');fs.mkdirSync(out,{recursive:true});const report={checks:[],errors:[]};const check=(name,pass,detail)=>report.checks.push({name,pass,detail});
(async()=>{const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
for(const fallback of [false,true]){const ctx=await b.newContext({viewport:{width:600,height:600},serviceWorkers:'block'});await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(fallback&&u.pathname==='/art.js')return r.fulfill({contentType:'application/javascript',body:'/* Deliberately missing optional art */'});return r.continue();});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(targetUrl.href);await p.waitForFunction(()=>window.__pitch);await p.evaluate(()=>{__pitch.game.settings.sound=false;__pitch.start('aur','azc');__pitch.nav('match');__pitch.hold();});await p.waitForFunction(()=>__pitch.r3d()?.ready);
if(fallback){const state=await p.evaluate(()=>{__pitch.render();const r=__pitch.r3d();return{calls:r.renderer.info.render.calls,healthy:!r.renderer.getContext().isContextLost(),material:r.sides.home.torso.material.type,ballRadius:r.ballRadius};});check('Missing optional art retains healthy legacy models',state.healthy&&state.calls>0&&state.material==='MeshLambertMaterial'&&state.ballRadius===.85,state);await p.screenshot({path:path.join(out,'missing-art.png')});await ctx.close();continue;}
const pairs=await p.evaluate(()=>{const h=__pitch,result=[];for(const home of h.TEAMS)for(const away of h.TEAMS){if(home.id===away.id)continue;h.start(home.id,away.id);h.nav('match');h.hold();h.render();const g=h.game,r=h.r3d(),c1=new r.T.Color(),c2=new r.T.Color();r.sides.home.torso.getColorAt(5,c1);r.sides.away.torso.getColorAt(5,c2);result.push({home:home.id,away:away.id,contrast:Math.hypot(c1.r-c2.r,c1.g-c2.g,c1.b-c2.b),distinctTextures:r.sides.home.kitMat.map.uuid!==r.sides.away.kitMat.map.uuid});}return result;});check('Every opposing kit pairing retains different colors and patterns',pairs.every(x=>x.contrast>.1&&x.distinctTextures),{pairs:pairs.length,minimumLinearColorDistance:Math.min(...pairs.map(x=>x.contrast))});
const buffers=await p.evaluate(()=>{const r=__pitch.r3d(),rows=[];for(const[n,m]of Object.entries(r.sides.home)){if(!m.geometry)continue;const g=m.geometry;let degenerate=0;const a=new r.T.Vector3(),b=new r.T.Vector3(),c=new r.T.Vector3();for(let i=0;i<(g.index?.count||g.attributes.position.count);i+=3){a.fromBufferAttribute(g.attributes.position,g.index?g.index.getX(i):i);b.fromBufferAttribute(g.attributes.position,g.index?g.index.getX(i+1):i+1);c.fromBufferAttribute(g.attributes.position,g.index?g.index.getX(i+2):i+2);if(b.sub(a).cross(c.sub(a)).lengthSq()<1e-14)degenerate++;}rows.push({name:n,finite:Object.values(g.attributes).every(a=>Array.from(a.array).every(Number.isFinite)),degenerate});}return rows;});check('All player buffers finite and triangles nondegenerate',buffers.every(x=>x.finite&&!x.degenerate),buffers);
await p.evaluate(()=>{__pitch.start('aur','azc');__pitch.nav('match');__pitch.hold();});
const gait=await p.evaluate(()=>{const h=__pitch,r=h.r3d(),rows=[];for(const phase of [0,Math.PI/2,Math.PI,Math.PI*1.5]){for(const side of[h.game.home,h.game.away])for(const p of side.players){p.runPhase=phase;p.vx=8;p.vy=0;}h.render();rows.push({phase,finite:Object.values(r.sides).every(side=>Object.values(side).filter(x=>x.isInstancedMesh).every(m=>Array.from(m.instanceMatrix.array).every(Number.isFinite)))});}const before={geom:r.renderer.info.memory.geometries,tex:r.renderer.info.memory.textures};for(let i=0;i<100;i++)h.render();return{rows,stable:before.geom===r.renderer.info.memory.geometries&&before.tex===r.renderer.info.memory.textures};});check('Full gait cycle and repeated frames stay finite and cached',gait.rows.every(x=>x.finite)&&gait.stable,gait);
// Inspect the actual instanced meshes at useful design scale, without rebuilding them.
await p.evaluate(()=>{const h=__pitch,r=h.r3d(),g=h.game;for(const side of[g.home,g.away])side.players.forEach((p,i)=>{p.x=side===g.home?42:46;p.y=52.5+i*12;p.heading=2.03;p.vx=p.vy=0;});g.activeId=null;g.ball.owner=null;g.ball.x=44;g.ball.y=50;g.ball.z=0;const cam=r.camera;cam.position.set(-8,8,16);cam.lookAt(0,2,0);cam.fov=31;cam.updateProjectionMatrix();h.render();});await p.screenshot({path:path.join(out,'player-detail.png')});
await p.evaluate(()=>{__pitch.gfx('2D');__pitch.render();});check('Existing Canvas2D fallback still draws',await p.locator('#pitch').isVisible());await p.screenshot({path:path.join(out,'canvas2d.png')});await ctx.close();}
}catch(e){report.error=e.stack;process.exitCode=1;}finally{await b.close();report.failed=report.checks.filter(x=>!x.pass);report.passed=!report.error&&!report.errors.length&&!report.failed.length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(!report.passed)process.exitCode=1;}})();
