/* Isolated browser regressions. No cloud requests or personal saves are used. */
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/kgood/.codex/skills/develop-web-game/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const url=process.env.PITCH_URL||'http://127.0.0.1:5223',out=process.env.PITCH_EVIDENCE||path.resolve(__dirname,'../../.visual-review/next-trio/glasspitch/tests');
fs.mkdirSync(out,{recursive:true});const results=[],errors=[];
function check(name,value,detail){results.push({name,pass:!!value,detail});assert.ok(value,name+' '+JSON.stringify(detail||''));}
(async()=>{const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader']});try{
const c=await b.newContext({viewport:{width:600,height:600},deviceScaleFactor:1});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith(url)?r.continue():r.abort());await p.goto(url);await p.waitForFunction(()=>window.__pitch);
await p.locator('#title [data-action="choose-teams"]').click();await p.waitForTimeout(40);check('Team selection starts on Select',await p.evaluate(()=>document.activeElement.dataset.action==='team-confirm'));
await p.evaluate(()=>document.activeElement.click());check('Focused pinch selects first team',await p.evaluate(()=>__pitch.game.ts.step===1));await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await p.waitForTimeout(40);check('Lineups default to Kick Off',await p.evaluate(()=>document.activeElement.dataset.action==='kickoff-go'));await p.keyboard.press('Enter');await p.waitForFunction(()=>__pitch.r3d()?.ready);
await p.evaluate(()=>{window.fixture=()=>{__pitch.game.settings.sound=false;__pitch.game.settings.setPieces=false;__pitch.start('sol','vrd');__pitch.nav('match');const g=__pitch.game;cancelAnimationFrame(g.rafId);g.running=false;g.guardUntil=0;g.settings.sound=false;g.settings.setPieces=false;return g;};fixture();});
let x=await p.evaluate(()=>{const g=__pitch.game;const r=__pitch.r3d();return {calls:r.renderer.info.render.calls,triangles:r.renderer.info.render.triangles,dpr:r.renderer.getPixelRatio(),shadow:r.renderer.shadowMap.enabled,healthy:!r.renderer.getContext().isContextLost()};});check('Bounded healthy 3D',x.healthy&&x.calls<90&&x.triangles<45000&&x.dpr===1&&!x.shadow,x);
await p.evaluate(()=>document.querySelector('[data-action="match-menu"]').click());const t=await p.evaluate(()=>__pitch.game.clockSec);await p.evaluate(()=>advanceTime(10000));check('Menu pauses simulation and rendering loop',await p.evaluate(t=>__pitch.game.screen==='pause'&&__pitch.game.clockSec===t&&!__pitch.game.running,t));
await p.waitForTimeout(40);check('Resume is first pause action',await p.evaluate(()=>document.activeElement.dataset.action==='resume'));await p.evaluate(()=>document.activeElement.click());await p.evaluate(()=>{cancelAnimationFrame(__pitch.game.rafId);__pitch.game.running=false;__pitch.game.guardUntil=0;});
for(const k of ['ArrowUp','ArrowDown','ArrowUp','ArrowDown']){await p.keyboard.press(k);await p.waitForTimeout(70);}check('D-pad pause chord',await p.evaluate(()=>__pitch.game.screen==='pause'));
await p.locator('[data-action="restart-match"]').click();check('Restart is confirmed',await p.evaluate(()=>__pitch.game.screen==='confirm'));await p.waitForTimeout(40);await p.keyboard.press('Enter');check('Default confirmation cancels',await p.evaluate(()=>__pitch.game.screen==='pause'));
await p.evaluate(()=>fixture());await p.evaluate(()=>window.dispatchEvent(new Event('blur')));check('Backgrounding pauses and clears held input',await p.evaluate(()=>__pitch.game.screen==='pause'&&Object.keys(__pitch.game.keys).length===0));
const steering=await p.evaluate(()=>{const result=[];for(const [key,axis,sign]of [['ArrowUp','x',1],['ArrowDown','x',-1],['ArrowLeft','y',-1],['ArrowRight','y',1]]){const g=fixture(),a=g.home.players[6];g.activeId=a.id;g.activeLockT=99;a.x=44;a.y=60;g.ball.owner=null;g.ball.x=70;g.ball.y=30;const before=a[axis];g.keys[key]=true;__pitch.simulate(.25);result.push({key,delta:(a[axis]-before)*sign});}return result;});for(const r of steering)check('Screen-relative '+r.key,r.delta>0,r);
check('Swipe expires by simulation time',await p.evaluate(()=>{const g=fixture();__pitch.steer('right');advanceTime(1000);return g._elapsed-g.lastSteerT>.75;}));
check('Near-ball pinch attempts tackle',await p.evaluate(()=>{const g=fixture(),a=g.home.players[6],o=g.away.players[6];g.activeId=a.id;a.x=44;a.y=52;o.x=45;o.y=52;g.ball.owner=o.id;g.ball.x=45;g.ball.y=52;a.tackleCd=0;__pitch.tap();return a.tackleCd>0;}));
check('Far pinch switches player',await p.evaluate(()=>{const g=fixture();g.activeId=g.home.players[1].id;g.ball.owner=null;g.ball.x=70;g.ball.y=30;const id=g.activeId;__pitch.tap();return g.activeId!==id;}));
check('Possession reception selects carrier',await p.evaluate(()=>{const g=fixture(),a=g.home.players[8];g.ball.owner=a.id;g.activeId=g.home.players[2].id;__pitch.simulate(.05);return g.activeId===a.id;}));
check('Pass releases ball and counts attempt',await p.evaluate(()=>{const g=fixture(),a=g.home.players[6];a.x=44;a.y=65;g.activeId=a.id;g.ball.owner=a.id;__pitch.tap();return g.ball.owner===null&&Math.hypot(g.ball.vx,g.ball.vy)>0&&g.passStat.home.att===1;}));
check('Shoot releases shot in range',await p.evaluate(()=>{const g=fixture(),a=g.home.players[8];a.x=44;a.y=20;g.activeId=a.id;g.ball.owner=a.id;__pitch.tap();return g.ball.owner===null&&g.stats.shots.home===1;}));
check('Touch focused click performs action',await p.evaluate(()=>{const g=fixture(),a=g.home.players[8];a.x=44;a.y=20;g.activeId=a.id;g.ball.owner=a.id;document.querySelector('.touch-pinch').click();return g.stats.shots.home===1;}));
const goal=await p.evaluate(()=>{const g=fixture();for(const a of [...g.home.players,...g.away.players]){a.x=10;a.y=50;}g.ball.owner=null;g.ball.x=44;g.ball.y=1;g.ball.vy=-30;g.ball.vx=0;g.ball.z=0;g.lastTouch='home';__pitch.simulate(.08);const before={score:g.home.score,phase:g.phase};__pitch.saveMatch();const saved=JSON.parse(localStorage.getItem('glasspitch_match_v1'));g.home.score=9;const resumed=__pitch.resume();__pitch.nav('match');cancelAnimationFrame(g.rafId);g.running=false;__pitch.simulate(4);return {before,resumed,savedPhase:saved.phase,score:g.home.score,phase:g.phase,x:g.ball.x,y:g.ball.y};});check('Goal counted once',goal.before.score===1&&goal.before.phase==='goal',goal);check('Goal celebration save resumes through kickoff',goal.resumed&&goal.savedPhase==='goal'&&goal.score===1&&goal.phase==='play'&&goal.y>1,goal);
check('Throw-in awards opposite side and resumes',await p.evaluate(()=>{const g=fixture();g.ball.owner=null;g.ball.x=.1;g.ball.y=40;g.ball.vx=-20;g.ball.vy=0;g.lastTouch='home';__pitch.simulate(.05);const phase=g.phase;__pitch.simulate(1);return phase==='restart'&&g.lastTouch==='away'&&g.phase==='play';}));
check('Second half reverses attacking ends',await p.evaluate(()=>{const g=fixture();const a=__pitch.atkUp('home');__pitch.secondHalf();cancelAnimationFrame(g.rafId);g.running=false;return a===true&&__pitch.atkUp('home')===false&&g.half===2;}));
check('Halftime stops time and saves break',await p.evaluate(()=>{const g=fixture();g.clockSec=2699;advanceTime(5000);return g.screen==='halftime'&&g.clockSec===2700&&JSON.parse(localStorage.getItem('glasspitch_match_v1')).resumeScreen==='halftime';}));
await p.reload();await p.waitForFunction(()=>window.__pitch);await p.locator('#title-continue').click();check('Reload Continue opens halftime',await p.evaluate(()=>__pitch.game.screen==='halftime'&&__pitch.game.half===1));
await p.locator('[data-action="resume-second"]').click();await p.evaluate(()=>{cancelAnimationFrame(__pitch.game.rafId);__pitch.game.running=false;});check('Second half starts at 45 minutes',await p.evaluate(()=>__pitch.game.half===2&&__pitch.game.clockSec>=2700&&__pitch.game.clockSec<2705));
check('Full-time record awarded exactly once',await p.evaluate(()=>{const g=__pitch.game,before=g.record.w;__pitch.finishMatch(2,1);__pitch.finishMatch(2,1);return g.record.w===before+1&&g.screen==='result'&&!__pitch.hasSaved();}));
await p.screenshot({path:path.join(out,'result.png')});
// Replay an existing-style v3 snapshot through the public restore path.
check('Legacy v3 preserves positions and player skills',await p.evaluate(()=>{__pitch.start('sol','vrd');const g=__pitch.game;__pitch.saveMatch();const snap=JSON.parse(localStorage.getItem('glasspitch_match_v1'));delete snap.elapsed;delete snap.seed;delete snap.matchDetails;delete snap.resumeScreen;localStorage.setItem('glasspitch_match_v1',JSON.stringify(snap));return __pitch.resume()&&JSON.stringify(g.home.players)===JSON.stringify(snap.home.players);}));
check('Malformed snapshot rejected without partial mutation',await p.evaluate(()=>{const before=JSON.stringify(__pitch.game.home);const s=JSON.parse(localStorage.getItem('glasspitch_match_v1'));s.home.players[0].x='bad';localStorage.setItem('glasspitch_match_v1',JSON.stringify(s));return !__pitch.resume()&&JSON.stringify(__pitch.game.home)===before;}));
check('Career boosts do not compound on Continue',await p.evaluate(()=>{__pitch.startCareer('sol');__pitch.game.career.boosts={ATT:4,MID:2,DEF:3,PAC:5,GK:1};__pitch.start('sol','vrd');__pitch.game.matchMode='career';for(const p of __pitch.game.home.players){p.pace+=5;p.shoot+=4;p.def+=3;}__pitch.saveMatch();const a=JSON.stringify(__pitch.game.home.players);for(let i=0;i<4;i++){if(!__pitch.resume())return false;__pitch.saveMatch();}return JSON.stringify(__pitch.game.home.players)===a;}));
const matches=await p.evaluate(()=>{const traces=[];for(let i=0;i<5;i++){const g=__pitch.game;g.settings.length='Short';g.settings.setPieces=false;__pitch.start(i%2?'aur':'sol',i%2?'crv':'vrd');__pitch.nav('match');cancelAnimationFrame(g.rafId);g.running=false;__pitch.allAI(true);for(let j=0;j<12&&g.screen!=='result';j++){__pitch.simulate(30);if(g.screen==='halftime'){__pitch.secondHalf();cancelAnimationFrame(g.rafId);g.running=false;__pitch.allAI(true);}if(g.screen==='setpiece'){__pitch.spForce('miss');}}traces.push({screen:g.screen,score:[g.home.score,g.away.score],clock:g.clockSec,finite:[...g.home.players,...g.away.players].every(a=>[a.x,a.y,a.vx,a.vy,a.stam].every(Number.isFinite))});}return traces;});for(const [i,m]of matches.entries())check('Simulated full match '+(i+1),m.screen==='result'&&m.clock===5400&&m.finite,m);
await p.evaluate(()=>{__pitch.start('sol','vrd');__pitch.nav('match');});await p.screenshot({path:path.join(out,'match.png')});await p.locator('[data-action="match-menu"]').first().click();await p.screenshot({path:path.join(out,'pause.png')});
check('No JavaScript errors',errors.length===0,errors);await c.close();
for(const phone of [false,true]){const ctx=await b.newContext({viewport:phone?{width:390,height:844}:{width:600,height:600},isMobile:phone,hasTouch:phone});const q=await ctx.newPage();await q.goto(url);await q.waitForFunction(()=>window.__pitch);for(const screen of ['title','team-select','settings','how']){if(screen==='team-select')await q.locator('#title [data-action="choose-teams"]').click();else await q.evaluate(s=>__pitch.nav(s),screen);await q.screenshot({path:path.join(out,`${screen}-${phone?'phone':'display'}.png`)});const fit=await q.evaluate(()=>{const s=document.querySelector('.screen:not(.hidden)').getBoundingClientRect();return s.left>=-.5&&s.right<=innerWidth+.5&&s.top>=-.5&&s.bottom<=innerHeight+.5;});check(`${screen} ${phone?'phone':'display'} fits`,fit);}if(phone){await q.evaluate(()=>{__pitch.start('sol','vrd');__pitch.nav('match');});await q.waitForFunction(()=>__pitch.r3d()?.ready);const sizes=await q.locator('.touch-btn,.touch-menu').evaluateAll(es=>es.map(e=>({label:e.textContent.trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));check('Phone touch targets are at least 44px',sizes.every(r=>r.w>=44&&r.h>=44),sizes);await q.screenshot({path:path.join(out,'match-phone.png')});await q.locator('.touch-menu').tap();check('Phone Menu tap pauses',await q.evaluate(()=>__pitch.game.screen==='pause'));}await ctx.close();}
}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({results,errors,passed:results.filter(r=>r.pass).length},null,2));await b.close();}console.log(JSON.stringify({passed:results.length,out}));})().catch(e=>{console.error(e);process.exitCode=1});
