/* Stateful competition fixtures plus real Continue/menu actions; disposable storage only. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||require('node:path').join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const url=process.env.PITCH_URL||'http://127.0.0.1:5261',out=process.env.PITCH_EVIDENCE||path.resolve(__dirname,'../../.visual-review/glasspitch-round2/systems');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader']}),ctx=await browser.newContext({viewport:{width:600,height:600}}),p=await ctx.newPage(),report={checks:[],errors:[],external:[]};await ctx.route('**/*',r=>{if(new URL(r.request().url()).origin===url)return r.continue();report.external.push(new URL(r.request().url()).origin);return r.abort();});p.on('pageerror',e=>report.errors.push(e.message));const check=(name,a,b=true)=>{assert.deepEqual(a,b,name);report.checks.push({name,pass:true});};const ev=f=>p.evaluate(f);const click=a=>p.locator('.screen:not(.hidden) [data-action="'+a+'"]').first().click();const reload=async()=>{await p.reload();await p.waitForFunction(()=>window.__pitch);};
await p.goto(url);await p.waitForFunction(()=>window.__pitch);
try{
 for(const [kind,start,play]of [['cup','startCup','cupPlay'],['league','startLeague','leaguePlay'],['career','startCareer','careerAdvance'],['worldcup','startWorldCup','worldcupPlay']]){
  const snap=await p.evaluate(({kind,start,play})=>{const h=__pitch,g=h.game;g.settings.sound=false;g.settings.gfx='2D';h[start]('sol');h[play]();h.hold();g.clockSec=1234;g.home.score=3;g.away.score=1;h.saveMatch();return JSON.parse(localStorage.glasspitch_match_v1);},{kind,start,play});await reload();await click('resume-saved');await ev(()=>__pitch.hold());
  const restored=await ev(()=>{const g=__pitch.game;return {mode:g.matchMode,home:g.home.teamId,away:g.away.teamId,score:[g.home.score,g.away.score],context:g.matchContext};});check(kind+' Continue restores exact fixture/score/context',restored,{mode:kind,home:snap.home.teamId,away:snap.away.teamId,score:[3,1],context:snap.matchContext});
  await p.evaluate(start=>{__pitch.nav('title');__pitch[start]('sol');__pitch.saveMatch();},start);check(kind+' replacement cannot resurrect previous saved match',await ev(()=>__pitch.hasSaved()),false);
  await p.evaluate(s=>localStorage.setItem('glasspitch_match_v1',JSON.stringify(s)),snap);check(kind+' stale same-team snapshot rejected after reset',await ev(()=>__pitch.resume()),false);
  await ev(()=>{__pitch.clearMatch();__pitch.start('sol','vrd');__pitch.hold();__pitch.saveMatch();});const friendly=await ev(()=>localStorage.glasspitch_match_v1);await p.evaluate(start=>__pitch[start]('vrd'),start);check(kind+' replacement preserves unrelated Friendly save',await ev(()=>localStorage.glasspitch_match_v1),friendly);
 }
 // True legacy v3 shape: no context and no competition identity.
 await ev(()=>{const h=__pitch,g=h.game;h.startLeague('sol');h.leaguePlay();h.hold();h.saveMatch();const s=JSON.parse(localStorage.glasspitch_match_v1);delete s.matchContext;delete g.league.saveId;const store=JSON.parse(localStorage.glasspitch_v1);delete store.league.saveId;localStorage.setItem('glasspitch_v1',JSON.stringify(store));localStorage.setItem('glasspitch_match_v1',JSON.stringify(s));g.home=null;g.away=null;});await reload();await click('resume-saved');await ev(()=>__pitch.hold());check('legacy v3 competition accepted at matching unplayed fixture',await ev(()=>__pitch.game.matchMode==='league'&&!!__pitch.game.matchContext));await ev(()=>__pitch.saveMatch());await reload();check('legacy identity persists across repeated reopening',await ev(()=>__pitch.hasSaved()));
 for(const mode of ['cup','leagueCup','careerCup','worldcupKO']){
  await p.evaluate(mode=>{const h=__pitch,g=h.game;h.penFast(false);g.settings.sound=false;if(mode==='cup'){h.startCup('sol');h.cupPlay();}else if(mode==='leagueCup'){h.startLeague('sol');h.leagueCupPlay();}else if(mode==='careerCup'){h.startCareer('sol');h.careerCupPlay();}else{h.startWorldCup('sol');for(let i=0;i<3;i++){h.worldcupPlay();h.hold();h.finishMatch(2,0);}h.worldcupPlay();}h.hold();h.finishMatch(1,1);},mode);
  check(mode+' tie immediately has a resumable shootout',await ev(()=>__pitch.hasSaved()&&JSON.parse(localStorage.glasspitch_match_v1).kind==='shootout'));await reload();await click('resume-saved');check(mode+' Continue returns to shootout aim',await ev(()=>__pitch.game.screen==='shootout'&&__pitch.game.penalty.phase==='aim'));
  await ev(()=>{__pitch.game.guardUntil=0;document.querySelector('#shootout [data-action="mini-action"]').click();});const kick=await ev(()=>structuredClone(__pitch.game.penalty));await click('mini-menu');await reload();await click('resume-saved');check(mode+' scored kick/history survives paused reload',await ev(()=>{const c=__pitch.game.penalty;return {hs:c.hs,as:c.as,hk:c.hk,ak:c.ak,histH:c.histH,histA:c.histA};}),{hs:kick.hs,as:kick.as,hk:kick.hk,ak:kick.ak,histH:kick.histH,histA:kick.histA});await p.waitForFunction(()=>__pitch.game.penalty.turn==='away'&&__pitch.game.penalty.phase==='aim',null,{timeout:4000});check(mode+' resumed result advances to opponent turn',await ev(()=>__pitch.game.penalty.turn),'away');
  // Saved winner before its presentation timer: settlement must occur exactly once.
  await ev(()=>{const c=__pitch.game.penalty;Object.assign(c,{hk:5,ak:5,hs:4,as:3,histH:[true,true,true,true,false],histA:[true,true,true,false,false],phase:'done',winner:'home'});__pitch.saveMatch();});await reload();await click('resume-saved');await p.waitForFunction(()=>__pitch.game.screen!=='shootout',null,{timeout:5000});check(mode+' resumed winner settles and clears live snapshot',await ev(()=>!__pitch.hasSaved()));const state=await ev(()=>localStorage.glasspitch_v1);await reload();check(mode+' settlement persists once',await ev(()=>localStorage.glasspitch_v1),state);
 }
 // Standalone penalties entered through actual team-selection controls, no regulation match required.
 await ev(()=>{__pitch.clearMatch();__pitch.nav('title');});await click('goto-shootout');await click('team-confirm');await click('team-next');await click('team-confirm');check('standalone team flow selects standalone context',await ev(()=>__pitch.game.penalty._ctx),'standalone');await ev(()=>__pitch.saveMatch());await reload();await click('resume-saved');check('standalone shootout continues without regulation teams',await ev(()=>__pitch.game.screen==='shootout'&&__pitch.game.penalty._ctx==='standalone'));await p.screenshot({path:path.join(out,'shootout-continued.png')});
 // Every scheduled round can be entered and awarded; scores remain oriented to the bracket.
 const progress=await ev(()=>{const h=__pitch,g=h.game,rows=[];g.settings.gfx='2D';for(const [kind,start,play,read,n]of [['cup','startCup','cupPlay','cup',3],['league','startLeague','leaguePlay','league',14],['career','startCareer','careerAdvance','career',14],['worldcup','startWorldCup','worldcupPlay','worldcup',5]]){h[start]('sol');let entries=true;for(let i=0;i<n;i++){h[play]();h.hold();entries=entries&&g.screen==='lineups';h.finishMatch(2,0);}const obj=h[read]();rows.push({kind,entries,finished:!!(obj.champion||obj.done||obj.cur?.done||obj.stage==='done')});}for(const side of [0,1]){h.startCup('sol');const c=g.cup,at=c.rounds[0].indexOf('sol');[c.rounds[0][side],c.rounds[0][at]]=[c.rounds[0][at],c.rounds[0][side]];h.cupPlay();h.hold();h.finishMatch(2,0);rows.push({kind:'bracket'+side,score:c.scores[0][0],expected:side?[0,2]:[2,0],advancer:c.rounds[1][0]});}return rows;});for(const r of progress){if(r.score){check(r.kind+' score matches bracket orientation',r.score,r.expected);check(r.kind+' correct winner advances',r.advancer,'sol');}else{check(r.kind+' every round opens lineups',r.entries);check(r.kind+' complete schedule finishes',r.finished);}}
 check('no browser errors',report.errors,[]);check('no external requests',report.external,[]);
}catch(e){report.failure=e.stack;process.exitCode=1;console.error(e);}finally{fs.writeFileSync(path.join(out,'lifecycle-report.json'),JSON.stringify(report,null,2));await browser.close();console.log('Lifecycle: '+report.checks.length+' passed.');}})().catch(e=>{console.error(e);process.exit(1)});
