// Isolated browser regression for pinch/focus/Back navigation. Run against a
// locally served app with PITCH_URL; PITCH_EVIDENCE selects screenshots/report.
// PLAYWRIGHT_PATH may point at an installed Playwright package. The default
// paths match the development workspace; no cloud requests or personal saves
// are used. Input assertions use DOM clicks, keyboard events, and native browser
// Back. The single set-piece fixture uses an existing hook to create that state.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||require('node:path').join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const base=(process.env.PITCH_URL||'http://127.0.0.1:5271').replace(/\/$/,'');
const out=process.env.PITCH_EVIDENCE||path.resolve(__dirname,'../../.visual-review/glasspitch-band-audit/current');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader']}),checks=[],errors=[],external=[],traces=[];
 for(const [view,options]of[['600',{viewport:{width:600,height:600}}],['390',{viewport:{width:390,height:844},isMobile:true,hasTouch:true}]]){
  async function scenario(name,fn){const context=await browser.newContext({...options,serviceWorkers:'block'});await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==new URL(base).origin){external.push(u.origin+u.pathname);return r.abort();}if(u.pathname==='/neural-prior-page')return r.fulfill({contentType:'text/html',body:'<title>Previous page</title>Previous page'});return r.continue();});const page=await context.newPage();page.setDefaultTimeout(4000);page.on('pageerror',e=>errors.push({view,name,message:e.message}));
   const trace=[];await page.exposeFunction('recordNeuralEvent',event=>trace.push(event));await page.addInitScript(()=>document.addEventListener('click',e=>{const b=e.target.closest?.('[data-action]');if(b)window.recordNeuralEvent({action:b.dataset.action,detail:e.detail,focused:document.activeElement===b});},true));
   try{await page.goto(base);await page.waitForFunction(()=>window.__pitch);const ui={
    state:()=>page.evaluate(()=>({screen:__pitch.game.screen,focus:document.activeElement?.dataset.action||null,ts:{step:__pitch.game.ts.step,idx:__pitch.game.ts.idx,you:__pitch.game.ts.you,opp:__pitch.game.ts.opp},subOff:__pitch.game._subOff,clock:__pitch.game.clockSec,history:__pitch.game.history,score:__pitch.game.home?[__pitch.game.home.score,__pitch.game.away.score]:null})),
    target:action=>page.locator('[data-action="'+action+'"]:visible').first(),
    focus:async action=>{await page.locator('[data-action="'+action+'"]:visible').first().focus();assert.equal(await page.evaluate(()=>document.activeElement?.dataset.action),action);},
    activate:async(mode='pinch')=>{if(mode==='pinch')await page.evaluate(()=>document.activeElement.click());else await page.keyboard.press(mode==='Space'?' ':mode);},
    open:async(action,mode='pinch')=>{await page.locator('[data-action="'+action+'"]:visible').first().focus();if(mode==='pinch')await page.evaluate(()=>document.activeElement.click());else await page.keyboard.press(mode==='Space'?' ':mode);},
    screen:async expected=>assert.equal((await ui.state()).screen,expected),
    focusVisible:async()=>{const r=await page.evaluate(()=>{const e=document.activeElement,b=e.getBoundingClientRect();return{action:e.dataset.action,left:b.left,top:b.top,right:b.right,bottom:b.bottom,width:innerWidth,height:innerHeight};});assert.ok(r.right>r.left&&r.bottom>r.top&&r.left>=-1&&r.top>=-1&&r.right<=r.width+1&&r.bottom<=r.height+1,JSON.stringify(r));},
    pause:async()=>{await ui.open('quick-match');await ui.screen('match');await ui.open('match-menu');await ui.screen('pause');},
    subs:async()=>{await ui.pause();await ui.open('goto-subs');await ui.screen('subs');},
    screenshot:label=>page.screenshot({path:path.join(out,view+'-'+label+'.png')}),
    back:async key=>page.evaluate(key=>{document.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));document.dispatchEvent(new KeyboardEvent('keyup',{key,bubbles:true,cancelable:true}));},key),
   };await fn(page,ui);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Viewport must not overflow horizontally');checks.push({view,name,pass:true});}
   catch(e){checks.push({view,name,pass:false,error:e.message});try{await page.screenshot({path:path.join(out,view+'-failure-'+name.replace(/[^a-z0-9]+/gi,'-').slice(0,65)+'.png')});trace.push({failureState:await page.evaluate(()=>({url:location.href,screen:window.__pitch?.game.screen,focus:document.activeElement?.dataset.action,history:window.__pitch?.game.history,step:window.__pitch?.game.ts.step}))});}catch{}}
   traces.push({view,name,events:trace});await context.close();
  }
   for(const mode of['pinch','Enter','Space'])await scenario('repeated focused team arrows retain arrow via '+mode,async(p,u)=>{await u.open('choose-teams');await u.focus('team-next');const first=(await u.state()).ts.idx;for(let n=1;n<=3;n++){await u.activate(mode);const s=await u.state();assert.equal(s.screen,'team-select');assert.equal(s.ts.step,0);assert.equal(s.focus,'team-next');assert.equal(s.ts.idx,(first+n)%await p.evaluate(()=>__pitch.TEAMS.length));await u.focusVisible();}await u.screenshot('team-arrows-'+mode);});
  await scenario('physical arrows browse teams then pinch confirms',async(p,u)=>{await u.open('choose-teams');const initial=(await u.state()).ts.idx;await p.keyboard.press('ArrowRight');assert.notEqual((await u.state()).ts.idx,initial);assert.equal((await u.state()).focus,'team-confirm');await u.activate();assert.equal((await u.state()).ts.step,1);assert.equal((await u.state()).screen,'team-select');});
  for(const mode of['pinch','Escape','BrowserBack'])await scenario('opponent Back returns to selected own team via '+mode,async(p,u)=>{await u.open('choose-teams');await p.keyboard.press('ArrowRight');const own=(await u.state()).ts.idx;await u.activate('Space');assert.equal((await u.state()).ts.step,1);if(mode==='pinch')await u.open('back');else await u.back(mode);const s=await u.state();assert.equal(s.screen,'team-select');assert.equal(s.ts.step,0);assert.equal(s.ts.idx,own);assert.equal(s.focus,'team-confirm');await u.focusVisible();});
  await scenario('chosen teams reach lineups and kickoff with mixed pinch keys',async(p,u)=>{await u.open('choose-teams');await u.activate('Enter');await u.activate('Space');await u.screen('lineups');assert.equal((await u.state()).focus,'kickoff-go');await u.activate();await u.screen('match');assert.equal((await u.state()).focus,'match-action');await p.waitForFunction(()=>__pitch.r3d()?.renderer.info.render.calls>0);await p.evaluate(()=>__pitch.hold());await u.screenshot('kickoff');});
  await scenario('sub selection cancel and commit preserve usable focus and roster',async(p,u)=>{await u.subs();const off=await p.locator('#subs [data-action^="sub-off:"]').nth(2).getAttribute('data-action');await u.open(off);assert.match((await u.state()).focus,/^sub-on:/);await u.focusVisible();assert.equal((await u.state()).subOff,off.slice(8));await u.screenshot('bench-focus');await u.open('sub-cancel');assert.equal((await u.state()).focus,off);assert.equal((await u.state()).subOff,null);await u.activate();const on=(await u.state()).focus;assert.match(on,/^sub-on:/);const before=await p.evaluate(()=>({left:__pitch.game.home.subsLeft,clock:__pitch.game.clockSec}));await u.activate();await u.screen('subs');assert.match((await u.state()).focus,/^sub-off:/);const state=await p.evaluate(()=>({ids:__pitch.game.home.players.map(x=>x.id),left:__pitch.game.home.subsLeft,clock:__pitch.game.clockSec}));assert.equal(state.left,before.left-1);assert.ok(state.ids.includes(on.slice(7)));assert.ok(!state.ids.includes(off.slice(8)));assert.equal(new Set(state.ids).size,state.ids.length);assert.equal(state.clock,before.clock);await u.focusVisible();await u.screenshot('sub-committed');});
  await scenario('Auto-subs redraw keeps the toggle for the next pinch',async(p,u)=>{await u.subs();await u.focus('subs-auto');const before=await p.evaluate(()=>__pitch.game.settings.autoSub);await u.activate();assert.equal((await u.state()).focus,'subs-auto');assert.equal(await p.evaluate(()=>__pitch.game.settings.autoSub),!before);await u.activate();assert.equal((await u.state()).screen,'subs');assert.equal((await u.state()).focus,'subs-auto');assert.equal(await p.evaluate(()=>__pitch.game.settings.autoSub),before);});
  await scenario('returning from substitutions restores its pause-menu row',async(p,u)=>{await u.subs();await u.open('back');await u.screen('pause');assert.equal((await u.state()).focus,'goto-subs');await u.activate();await u.screen('subs');});
  await scenario('settings controls keep focus and Back restores Settings opener',async(p,u)=>{await u.open('goto-settings');await u.focus('cycle-difficulty');for(const mode of['pinch','Enter','Space']){const before=await p.evaluate(()=>__pitch.game.settings.difficulty);await u.activate(mode);assert.notEqual(await p.evaluate(()=>__pitch.game.settings.difficulty),before);assert.equal((await u.state()).focus,'cycle-difficulty');}await u.open('back');await u.screen('title');assert.equal((await u.state()).focus,'goto-settings');await u.activate();await u.screen('settings');});
  await scenario('canceling Reset Record restores its settings row and data',async(p,u)=>{await u.open('goto-settings');const before=await p.evaluate(()=>JSON.stringify(__pitch.game.record));await u.open('reset-record');await u.screen('confirm');assert.equal((await u.state()).focus,'confirm-cancel');await u.activate();await u.screen('settings');assert.equal((await u.state()).focus,'reset-record');assert.equal(await p.evaluate(()=>JSON.stringify(__pitch.game.record)),before);await u.focusVisible();});
  await scenario('restart cancel keeps match progress and restores Restart focus',async(p,u)=>{await u.open('quick-match');await p.evaluate(()=>advanceTime(2000));await u.open('match-menu');const before=await u.state();await u.open('restart-match');await u.screen('confirm');assert.equal((await u.state()).focus,'confirm-cancel');await u.activate();await u.screen('pause');const after=await u.state();assert.equal(after.focus,'restart-match');assert.equal(after.clock,before.clock);assert.deepEqual(after.score,before.score);await u.activate();await u.screen('confirm');await u.back('Escape');assert.equal((await u.state()).focus,'restart-match');assert.equal((await u.state()).clock,before.clock);});
  for(const key of['BrowserBack','GoBack','Backspace'])await scenario(key+' pauses live play; Escape resumes without losing progress',async(p,u)=>{await u.open('quick-match');await p.evaluate(()=>advanceTime(1000));await u.back(key);await u.screen('pause');const before=await u.state();await p.evaluate(()=>advanceTime(4000));await p.waitForTimeout(80);assert.equal((await u.state()).clock,before.clock);assert.deepEqual((await u.state()).score,before.score);const snap=await p.evaluate(()=>JSON.parse(localStorage.getItem('glasspitch_match_v1')));assert.equal(snap.clockSec,before.clock);await u.back('Escape');await u.screen('match');await p.evaluate(()=>__pitch.hold());assert.equal((await u.state()).clock,before.clock);});
  await scenario('Back from nested submenu returns exactly one level',async(p,u)=>{await u.subs();await u.back('BrowserBack');await u.screen('pause');assert.equal((await u.state()).focus,'goto-subs');await u.back('BrowserBack');await u.screen('title');assert.equal(await u.target('resume-saved').isVisible(),true);});
  await scenario('shootout pinch menu pauses; Escape resumes the same kick',async(p,u)=>{await u.open('goto-shootout');await u.activate('Enter');await u.activate('Space');await u.screen('shootout');const before=await p.evaluate(()=>JSON.stringify(__pitch.pen()));await u.open('mini-menu');await u.screen('mini-pause');await p.evaluate(()=>advanceTime(4000));assert.equal(await p.evaluate(()=>JSON.stringify(__pitch.pen())),before);await u.back('Escape');await u.screen('shootout');assert.equal(await p.evaluate(()=>JSON.stringify(__pitch.pen())),before);assert.equal((await u.state()).focus,'mini-action');await u.screenshot('shootout-resumed');});
  await scenario('native Back pauses then returns title and exits without trapping history',async(p,u)=>{await p.goto(base+'/neural-prior-page');await p.goto(base);await p.waitForFunction(()=>window.__pitch);await u.open('quick-match');await p.evaluate(()=>advanceTime(1000));const length=await p.evaluate(()=>history.length);await p.goBack({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__pitch?.game.screen==='pause',null,{timeout:2500});const saved=await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1'));for(let i=0;i<2;i++){await u.back('Escape');await u.screen('match');await p.evaluate(()=>__pitch.hold());assert.equal(await p.evaluate(()=>history.length),length);await p.goBack({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__pitch?.game.screen==='pause',null,{timeout:2500});}await p.goBack({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__pitch?.game.screen==='title',null,{timeout:2500});assert.ok(await p.evaluate(()=>!!localStorage.getItem('glasspitch_match_v1')));assert.equal(await u.target('resume-saved').isVisible(),true);assert.equal(new URL(p.url()).origin,new URL(base).origin);await p.goBack({waitUntil:'domcontentloaded'});await p.waitForURL(u=>u.pathname==='/neural-prior-page',{timeout:2500});assert.ok(saved);});
  await scenario('native Back from substitutions restores pause row then title',async(p,u)=>{await p.goto(base+'/neural-prior-page');await p.goto(base);await p.waitForFunction(()=>window.__pitch);await u.subs();await p.goBack({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__pitch?.game.screen==='pause',null,{timeout:2500});assert.equal((await u.state()).focus,'goto-subs');await p.goBack({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__pitch?.game.screen==='title',null,{timeout:2500});await p.goBack({waitUntil:'domcontentloaded'});await p.waitForURL(u=>u.pathname==='/neural-prior-page',{timeout:2500});});
  await scenario('saved substitution and match progress survive title and reload',async(p,u)=>{await u.subs();const off=await p.locator('#subs [data-action^="sub-off:"]').first().getAttribute('data-action');await u.open(off);const on=await p.locator('#subs [data-action^="sub-on:"]').first().getAttribute('data-action');await u.open(on);await u.open('back');const before=await p.evaluate(()=>({ids:__pitch.game.home.players.map(x=>x.id),left:__pitch.game.home.subsLeft,clock:__pitch.game.clockSec,score:[__pitch.game.home.score,__pitch.game.away.score]}));await u.open('quit-title');await p.reload();await p.waitForFunction(()=>window.__pitch);await u.open('resume-saved');await p.evaluate(()=>__pitch.hold());const after=await p.evaluate(()=>({ids:__pitch.game.home.players.map(x=>x.id),left:__pitch.game.home.subsLeft,clock:__pitch.game.clockSec,score:[__pitch.game.home.score,__pitch.game.away.score]}));assert.deepEqual(after.ids,before.ids);assert.equal(after.left,before.left);assert.deepEqual(after.score,before.score);assert.ok(after.clock>=before.clock&&after.clock-before.clock<1);});
   for(const action of['choose-teams','goto-watch'])await scenario(action+' lineup Back restores opponent selection, then own team',async(p,u)=>{await u.open(action);await p.keyboard.press('ArrowRight');const own=(await u.state()).ts.idx;await u.activate();await p.keyboard.press('ArrowRight');const opp=(await u.state()).ts.idx;await u.activate();await u.screen('lineups');await u.back('Escape');await u.screen('team-select');assert.equal((await u.state()).ts.step,1);assert.equal((await u.state()).ts.idx,opp);await u.back('Escape');await u.screen('team-select');assert.equal((await u.state()).ts.step,0);assert.equal((await u.state()).ts.idx,own);await u.back('Escape');await u.screen('title');assert.equal((await u.state()).focus,action);});
   await scenario('cancelled Watch setup leaves Play Now under player control',async(p,u)=>{await u.open('goto-watch');await u.activate();await u.activate();await u.screen('lineups');for(let i=0;i<3;i++)await u.back('Escape');await u.screen('title');await u.open('quick-match');await u.screen('match');await p.evaluate(()=>__pitch.hold());const s=await p.evaluate(()=>({mode:__pitch.game.matchMode,watch:__pitch.game.watching,allAI:__pitch.game._allAI}));assert.deepEqual(s,{mode:'friendly',watch:false,allAI:false});assert.equal((await u.state()).focus,'match-action');assert.equal(await u.target('match-action').isVisible(),true);});
   await scenario('Back from Watch preserves spectator state in the parked save',async(p,u)=>{await u.open('goto-watch');await u.activate();await u.activate();await u.activate();await u.screen('match');await u.back('BrowserBack');await u.screen('pause');await u.back('BrowserBack');await u.screen('title');const raw=await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1'));const saved=JSON.parse(raw);assert.equal(saved.watching,true);assert.equal(saved.allAI,true);await p.reload();await p.waitForFunction(()=>window.__pitch);assert.equal(await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1')),raw);await u.open('resume-saved');await u.screen('match');await p.evaluate(()=>__pitch.hold());assert.equal(await p.evaluate(()=>__pitch.game.watching&&__pitch.game._allAI),true);});
   for(const route of['restart','reload'])await scenario('Watch Take Control remains manual after '+route,async(p,u)=>{await u.open('goto-watch');await u.activate();await u.activate();await u.activate();await u.screen('match');await u.open('match-menu');await u.open('watch-toggle');await u.screen('match');await u.open('match-menu');if(route==='restart'){await u.open('restart-match');await u.screen('confirm');await u.open('confirm-accept');await u.screen('lineups');await u.activate();}else{await u.open('quit-title');await u.screen('title');const snap=await p.evaluate(()=>JSON.parse(localStorage.getItem('glasspitch_match_v1')));assert.equal(snap.watching,false);assert.equal(snap.allAI,false);await p.reload();await p.waitForFunction(()=>window.__pitch);await u.open('resume-saved');}await u.screen('match');await p.evaluate(()=>__pitch.hold());assert.deepEqual(await p.evaluate(()=>[__pitch.game.watching,__pitch.game._allAI]),[false,false]);assert.equal((await u.state()).focus,'match-action');assert.equal(await u.target('match-action').isVisible(),true);});
   await scenario('Back within bench choice cancels selection before leaving substitutions',async(p,u)=>{await u.subs();const off=await p.locator('#subs [data-action^="sub-off:"]').nth(2).getAttribute('data-action');await u.open(off);const before=await p.evaluate(()=>JSON.stringify(__pitch.game.home.players));await u.back('BrowserBack');await u.screen('subs');assert.equal((await u.state()).focus,off);assert.equal((await u.state()).subOff,null);assert.equal(await p.evaluate(()=>JSON.stringify(__pitch.game.home.players)),before);await u.back('BrowserBack');await u.screen('pause');assert.equal((await u.state()).focus,'goto-subs');});
   await scenario('last available substitution leaves Auto-subs focused instead of Back',async(p,u)=>{await u.subs();const count=await p.evaluate(()=>__pitch.game.home.subsLeft);assert.ok(count>0&&count<=5);for(let i=0;i<count;i++){const off=await p.locator('#subs [data-action^="sub-off:"]').first().getAttribute('data-action');await u.open(off);assert.match((await u.state()).focus,/^sub-on:/);await u.activate();assert.equal(await p.evaluate(()=>__pitch.game.home.subsLeft),count-i-1);}assert.equal((await u.state()).focus,'subs-auto');await u.activate();await u.screen('subs');assert.equal((await u.state()).focus,'subs-auto');await u.focusVisible();await u.screenshot('subs-exhausted');});
   await scenario('shootout result quit cancels its timer and reload resumes the saved kick',async(p,u)=>{await u.pause();await u.open('quit-title');await u.open('goto-shootout');await u.activate();await u.activate();await u.screen('shootout');await p.waitForTimeout(250);await u.open('mini-action');assert.equal(await p.evaluate(()=>__pitch.pen().phase),'result');await u.open('mini-menu');await u.screen('mini-pause');await u.open('quit-title');await u.screen('title');const raw=await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1'));const saved=JSON.parse(raw);assert.equal(saved.kind,'shootout');assert.equal(saved.penalty.hk,1);assert.equal(saved.penalty.ak,0);assert.equal(saved.penalty.phase,'result');await p.waitForTimeout(1300);await u.screen('title');assert.equal(await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1')),raw);await p.reload();await p.waitForFunction(()=>window.__pitch);assert.equal(await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1')),raw);await u.open('resume-saved');await u.screen('shootout');assert.deepEqual(await p.evaluate(()=>__pitch.pen()),saved.penalty);await p.waitForFunction(()=>__pitch.pen().phase==='aim',null,{timeout:2000});assert.equal(await p.evaluate(()=>__pitch.pen().turn),'away');assert.equal(await p.evaluate(()=>__pitch.pen().hk),1);await u.screenshot('shootout-saved-result-resumed');});
   await scenario('fixture set-piece stays parked on title and reloads its exact aim',async(p,u)=>{await u.open('quick-match');await p.evaluate(()=>{__pitch.hold();__pitch.spStart('fk');});await u.screen('setpiece');await p.waitForTimeout(250);await p.keyboard.press('ArrowRight');await u.open('mini-menu');await u.open('quit-title');await u.screen('title');const raw=await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1'));const saved=JSON.parse(raw);assert.equal(saved.resumeScreen,'setpiece');assert.equal(saved.setPiece.phase,'aim');await p.reload();await p.waitForFunction(()=>window.__pitch);assert.equal(await p.evaluate(()=>localStorage.getItem('glasspitch_match_v1')),raw);await u.open('resume-saved');await u.screen('setpiece');assert.deepEqual(await p.evaluate(()=>__pitch.setpiece()),saved.setPiece);assert.equal((await u.state()).focus,'mini-action');});
   if(view==='390')await scenario('real touch team-arrow taps keep browsing instead of confirming',async(p,u)=>{await u.target('choose-teams').tap();const initial=(await u.state()).ts.idx;for(let i=1;i<=3;i++){await u.target('team-next').tap();assert.equal((await u.state()).ts.step,0);assert.equal((await u.state()).focus,'team-next');assert.equal((await u.state()).ts.idx,(initial+i)%await p.evaluate(()=>__pitch.TEAMS.length));}});
 }
 const detailZero=traces.flatMap(t=>t.events).filter(e=>e.action&&e.detail===0).length;
 checks.push({view:'both',name:'pinch was delivered as activeElement.click detail0',pass:detailZero>20,detailZero});
 checks.push({view:'both',name:'no runtime errors or external requests',pass:errors.length===0&&external.length===0});
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({base,checks,errors,external,traces},null,2));console.log(JSON.stringify({base,passed:checks.filter(c=>c.pass).length,total:checks.length,failed:checks.filter(c=>!c.pass),detailZero,errors}));await browser.close();if(checks.some(c=>!c.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
