const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||require('node:path').join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const base=process.env.PITCH_URL||'http://127.0.0.1:5261';
const out=process.env.PITCH_EVIDENCE||path.resolve(__dirname,'../../.visual-review/glasspitch-round2/systems/tutorial');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader']}),checks=[],errors=[],outbound=[];
 const context=await browser.newContext({viewport:{width:600,height:600}});
 const isolate=async c=>{await c.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(base).origin)return r.continue();outbound.push(r.request().url());return r.abort();});};
 await isolate(context);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
 const run=fn=>p.evaluate(fn),check=async(name,fn)=>{try{await fn();checks.push({name,pass:true});}catch(e){checks.push({name,pass:false,error:e.message});}};
 await p.goto(base);await p.waitForFunction(()=>window.__pitch);
 const tutorial=async()=>{await run(()=>__pitch.nav('title'));await p.locator('#title [data-action="goto-how"]').click();await p.locator('[data-action="start-tutorial"]').click();await run(()=>{__pitch.hold();__pitch.game.guardUntil=0;});};
 const saved=()=>run(()=>localStorage.getItem('glasspitch_match_v1'));
 // Known score/time fixture, saved through the real serializer. No remote or personal save is used.
 await run(()=>{const h=__pitch,g=h.game;h.start('sol','vrd');h.nav('match');h.hold();g.home.score=3;g.away.score=1;g.clockSec=100;h.saveMatch();});
 const original=await saved();
 await check('tutorial excludes active practice from all save attempts',async()=>{await tutorial();await run(()=>{__pitch.simulate(3);__pitch.saveMatch();});assert.equal(await saved(),original);});
 await check('blur skips practice without changing the existing saved match',async()=>{await run(()=>window.dispatchEvent(new Event('blur')));assert.equal(await run(()=>__pitch.game.screen),'title');assert.equal(await run(()=>__pitch.game.matchMode),'tutorial');assert.equal(await saved(),original);});
 await check('pagehide after tutorial skip preserves every saved field',async()=>{await run(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await saved(),original);});
 await check('reload and Continue recover the original score and time',async()=>{await p.reload();await p.waitForFunction(()=>window.__pitch);await p.locator('[data-action="resume-saved"]').click();await run(()=>__pitch.hold());assert.deepEqual(await run(()=>[__pitch.game.home.score,__pitch.game.away.score,Math.floor(__pitch.game.clockSec)]),[3,1,100]);});
 await check('explicit Menu skips practice and subsequent pagehide stays non-saveable',async()=>{await tutorial();await p.locator('#match [data-action="match-menu"]').click();await run(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await saved(),original);});
 await check('normal Play Now after skip creates a real resumable match',async()=>{await p.locator('#title [data-action="quick-match"]').click();await run(()=>__pitch.hold());assert.equal(await run(()=>__pitch.game.screen),'match');assert.equal(await run(()=>__pitch.game.matchMode),'friendly');const snap=JSON.parse(await saved());assert.equal(snap.matchMode,'friendly');assert.equal(snap.home.score,0);assert.equal(snap.away.score,0);assert.equal(snap.clockSec,0);assert.notEqual(await saved(),original);});
 const fresh=await saved();
 await check('practice completion also stays non-saveable',async()=>{await tutorial();await run(()=>{__pitch.game.tutorial.step=4;__pitch.tap();window.dispatchEvent(new Event('pagehide'));});assert.equal(await run(()=>__pitch.game.screen),'title');assert.equal(await saved(),fresh);});
 await check('practice resets previous spectator mode and elapsed pass timers',async()=>{await run(()=>{const g=__pitch.game;g.watching=true;g._allAI=true;g._elapsed=900;g._passUntil=950;g._passTo='stale';g._replay={frames:[],i:0};g._replayDelay=1;});await tutorial();assert.deepEqual(await run(()=>{const g=__pitch.game;return[g.watching,g._allAI,g._elapsed,g._passUntil,g._passTo,g._replay,g._replayDelay];}),[false,false,0,0,null,null,null]);});
 await run(()=>{window.testPad={connected:true,axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[testPad]});});
 const pad=xy=>p.evaluate(xy=>{testPad.axes=xy;__pitch.pollPad();},xy);
 await check('held controller direction counts one tutorial input, not every poll',async()=>{await pad([1,0]);await run(()=>{for(let i=0;i<60;i++)__pitch.pollPad();});assert.equal(await run(()=>__pitch.tutorial().steerCount),1);});
 await check('distinct controller starts advance the steering lesson',async()=>{await pad([0,0]);await pad([0,-1]);await pad([0,0]);await pad([-1,0]);await pad([0,0]);assert.equal(await run(()=>__pitch.tutorial().steerCount),3);await run(()=>__pitch.simulate(1.1));assert.equal(await run(()=>__pitch.tutorial().step),1);});
 await check('controller can perform the following pass lesson',async()=>{await run(()=>{testPad.buttons[0].pressed=true;__pitch.pollPad();testPad.buttons[0].pressed=false;__pitch.pollPad();__pitch.simulate(.1);});assert.equal(await run(()=>__pitch.tutorial().step),2);});
 await p.screenshot({path:path.join(out,'controller-tutorial.png')});
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await isolate(phoneContext);const phone=await phoneContext.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base);await phone.waitForFunction(()=>window.__pitch);await phone.locator('#title [data-action="goto-how"]').tap();await phone.locator('[data-action="start-tutorial"]').tap();await phone.evaluate(()=>{__pitch.hold();__pitch.game.guardUntil=0;});
 const cdp=await phoneContext.newCDPSession(phone),touch=async(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y}]});
 await check('repeated touch drag in one direction counts one start',async()=>{await touch('touchStart',150,210);await touch('touchMove',180,210);await touch('touchMove',210,210);assert.equal(await phone.evaluate(()=>__pitch.tutorial().steerCount),1);});
 await check('touch drag changes advance the steering lesson',async()=>{await touch('touchMove',210,240);await touch('touchMove',180,240);await touch('touchEnd');assert.equal(await phone.evaluate(()=>__pitch.tutorial().steerCount),3);await phone.evaluate(()=>__pitch.simulate(1.1));assert.equal(await phone.evaluate(()=>__pitch.tutorial().step),1);});
 await check('skipping practice with no existing save cannot create Continue',async()=>{await phone.locator('[data-action="match-menu"]:visible').tap();await phone.evaluate(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await phone.evaluate(()=>localStorage.getItem('glasspitch_match_v1')),null);assert.equal(await phone.locator('#title [data-action="resume-saved"]').isVisible(),false);});
 await phone.screenshot({path:path.join(out,'phone-skipped.png')});
 await check('no runtime errors or external save requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(outbound,[]);});
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors,outbound},null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.pass).length,total:checks.length,failed:checks.filter(c=>!c.pass),errors}));await browser.close();if(checks.some(c=>!c.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
